- name: Auditoría Pre-Hardening en Windows
  hosts: all
  gather_facts: no
  tasks:
    - name: Copiar script PowerShell a la máquina
      ansible.windows.win_copy:
        src: ./run_audit.ps1
        dest: C:\scripts\run_audit.ps1

    - name: Ejecutar script de auditoría
      ansible.windows.win_shell: powershell.exe -ExecutionPolicy Bypass -File C:\scripts\run_audit.ps1















