- name: Auditoría Pre-Hardening en Windows
  hosts: all
  gather_facts: no
  tasks:
    - name: Crear la carpeta C:\scripts
      win_file:
        path: C:\scripts
        state: directory

    - name: Copiar script PowerShell a la máquina
      ansible.windows.win_copy:
        src: ./run_audit.ps1
        dest: C:\scripts\run_audit.ps1

    - name: Crear la carpeta C:\scripts\Windows-2016-CIS-Audit
      win_file:
        path: C:\scripts\Windows-2016-CIS-Audit
        state: directory

    - name: Copiar archivo goss.yml en la máquina
      ansible.windows.win_copy:
        src: ./goss.yml
        dest: C:\scripts\Windows-2016-CIS-Audit\goss.yml

    - name: Copiar archivo CIS.yml en la máquina
      ansible.windows.win_copy:
        src: ./CIS.yml
        dest: C:\scripts\Windows-2016-CIS-Audit\CIS.yml

    - name: Copiar archivo goss.exe en la máquina
      ansible.windows.win_copy:
        src: ./goss.exe
        dest: C:\scripts\goss.exe

    - name: Copiar archivos prereq_check en la maquina
      ansible.windows.win_copy:
        src: /home/morera/Ansible/ansible_quickstart/Windows-2019-CIS/Windows-2019-CIS-Audit/prereq_check
        dest: C:\scripts\Windows-2016-CIS-Audit\

    - name: Copiar archivos standalone_checks en la maquina
      ansible.windows.win_copy:
        src: /home/morera/Ansible/ansible_quickstart/Windows-2019-CIS/Windows-2019-CIS-Audit/standalone_checks
        dest: C:\scripts\Windows-2016-CIS-Audit\

    - name: Ejecutar script de auditoría
      ansible.windows.win_shell: powershell.exe -ExecutionPolicy Bypass -File C:\scripts\run_audit.ps1
